import type { BarMode, Equipment, MuscleGroup, TrackingType, WeightMode } from '@/domain/types';

export interface SeedExercise {
  id: string;
  name: string;
  muscle: MuscleGroup;
  secondary?: MuscleGroup[];
  equipment: Equipment;
  tracking?: TrackingType;
  weightMode?: WeightMode;
  barMode?: BarMode;
  barWeight?: number;
  unilateral?: boolean;
  rest?: number;
  aliases?: string[];
}

/**
 * Built-in exercise library (German names). The aliases contain the names
 * used in the original training notes, so importing them works out of the box.
 * IDs are stable — never change them, the app references them.
 */
export const SEED_EXERCISES: SeedExercise[] = [
  // --- Brust -----------------------------------------------------------------
  {
    id: 'ex-incline-chest-press-machine',
    name: 'Schrägbankdrücken an der Maschine',
    muscle: 'chest',
    secondary: ['shoulders', 'triceps'],
    equipment: 'machine',
    barMode: 'included',
    rest: 120,
    aliases: ['Schräg-Brustmaschine', 'Schräg Brustmaschine', 'Schrägbrustmaschine', 'Incline Chest Press'],
  },
  {
    id: 'ex-chest-press-machine',
    name: 'Brustpresse (Maschine)',
    muscle: 'chest',
    secondary: ['shoulders', 'triceps'],
    equipment: 'machine',
    barMode: 'included',
    rest: 120,
    aliases: ['Brustmaschine', 'Brustpresse', 'Chest Press'],
  },
  {
    id: 'ex-pec-deck',
    name: 'Butterfly (Maschine)',
    muscle: 'chest',
    equipment: 'machine',
    rest: 90,
    aliases: ['Butterfly', 'Butterfly Maschine', 'Pec Deck'],
  },
  {
    id: 'ex-cable-crossover-low',
    name: 'Kabel-Crossover von unten',
    muscle: 'chest',
    secondary: ['shoulders'],
    equipment: 'cable',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Kabel Crossover von unten', 'Cable Crossover von unten', 'Low Cable Fly'],
  },
  {
    id: 'ex-cable-crossover-high',
    name: 'Kabel-Crossover von oben',
    muscle: 'chest',
    equipment: 'cable',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Kabel Crossover', 'Kabel Crossover von oben', 'Cable Crossover'],
  },
  {
    id: 'ex-bench-press',
    name: 'Bankdrücken (Langhantel)',
    muscle: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 150,
    aliases: ['Bankdrücken', 'Flachbankdrücken', 'Bench Press'],
  },
  {
    id: 'ex-incline-bench-press',
    name: 'Schrägbankdrücken (Langhantel)',
    muscle: 'chest',
    secondary: ['shoulders', 'triceps'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 150,
    aliases: ['Schrägbankdrücken', 'Incline Bench Press'],
  },
  {
    id: 'ex-decline-bench-press',
    name: 'Negativbankdrücken',
    muscle: 'chest',
    secondary: ['triceps'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 120,
    aliases: ['Decline Bench Press'],
  },
  {
    id: 'ex-db-bench-press',
    name: 'Kurzhantel-Bankdrücken',
    muscle: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 120,
    aliases: ['Kurzhantel Bankdrücken', 'Dumbbell Bench Press'],
  },
  {
    id: 'ex-db-incline-press',
    name: 'Schrägbankdrücken (Kurzhantel)',
    muscle: 'chest',
    secondary: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 120,
    aliases: ['Kurzhantel Schrägbankdrücken'],
  },
  {
    id: 'ex-db-fly',
    name: 'Kurzhantel-Fliegende',
    muscle: 'chest',
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 90,
    aliases: ['Fliegende', 'Flys', 'Dumbbell Fly'],
  },
  {
    id: 'ex-smith-bench-press',
    name: 'Bankdrücken an der Multipresse',
    muscle: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: 'smith',
    rest: 120,
    aliases: ['Multipresse Bankdrücken', 'Smith Machine Bench Press'],
  },
  {
    id: 'ex-dips-chest',
    name: 'Dips',
    muscle: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 90,
    aliases: ['Barrendips', 'Dips Brust'],
  },
  {
    id: 'ex-push-ups',
    name: 'Liegestütze',
    muscle: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 60,
    aliases: ['Liegestütz', 'Push-ups', 'Pushups'],
  },

  // --- Rücken ----------------------------------------------------------------
  {
    id: 'ex-lat-pulldown',
    name: 'Latzug breit',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'cable',
    rest: 90,
    aliases: ['Latzug', 'Latziehen', 'Lat Pulldown'],
  },
  {
    id: 'ex-lat-pulldown-close',
    name: 'Latzug eng (V-Griff)',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'cable',
    rest: 90,
    aliases: ['Latzug eng', 'Close Grip Pulldown'],
  },
  {
    id: 'ex-pull-ups',
    name: 'Klimmzüge',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 120,
    aliases: ['Klimmzug', 'Pull-ups', 'Pullups'],
  },
  {
    id: 'ex-chin-ups',
    name: 'Klimmzüge (Untergriff)',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 120,
    aliases: ['Chin-ups', 'Chinups'],
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Rudern am Kabel (sitzend)',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'cable',
    rest: 90,
    aliases: ['Kabelrudern', 'Rudern sitzend', 'Seated Cable Row'],
  },
  {
    id: 'ex-machine-row',
    name: 'Rudermaschine (brustgestützt)',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'machine',
    rest: 90,
    aliases: ['Rudermaschine', 'Row Machine'],
  },
  {
    id: 'ex-one-arm-row',
    name: 'Einarmiges Rudern',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'dumbbell',
    unilateral: true,
    rest: 60,
    aliases: ['Rudern', 'Rudern einarmig', 'Kurzhantelrudern einarmig', 'One Arm Row'],
  },
  {
    id: 'ex-barbell-row',
    name: 'Langhantelrudern (vorgebeugt)',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 120,
    aliases: ['Langhantelrudern', 'Vorgebeugtes Rudern', 'Barbell Row'],
  },
  {
    id: 'ex-t-bar-row',
    name: 'T-Bar-Rudern',
    muscle: 'back',
    secondary: ['biceps'],
    equipment: 'barbell',
    barMode: 'excluded',
    rest: 120,
    aliases: ['T-Bar Rudern', 'T Bar Row'],
  },
  {
    id: 'ex-deadlift',
    name: 'Kreuzheben',
    muscle: 'back',
    secondary: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 180,
    aliases: ['Deadlift', 'Kreuzheben klassisch'],
  },
  {
    id: 'ex-back-extension',
    name: 'Rückenstrecker (Hyperextension)',
    muscle: 'back',
    secondary: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 60,
    aliases: ['Rückenstrecker', 'Hyperextensions', 'Hyperextension'],
  },
  {
    id: 'ex-straight-arm-pulldown',
    name: 'Überzüge am Kabel',
    muscle: 'back',
    equipment: 'cable',
    rest: 60,
    aliases: ['Straight Arm Pulldown', 'Pullover am Kabel'],
  },
  {
    id: 'ex-shrugs',
    name: 'Shrugs (Kurzhantel)',
    muscle: 'back',
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Shrugs', 'Schulterheben'],
  },

  // --- Schultern -------------------------------------------------------------
  {
    id: 'ex-ohp',
    name: 'Schulterdrücken (Langhantel)',
    muscle: 'shoulders',
    secondary: ['triceps'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 150,
    aliases: ['Military Press', 'Overhead Press', 'Schulterdrücken stehend'],
  },
  {
    id: 'ex-db-shoulder-press',
    name: 'Schulterdrücken (Kurzhantel)',
    muscle: 'shoulders',
    secondary: ['triceps'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 120,
    aliases: ['Schulterdrücken', 'Kurzhantel Schulterdrücken'],
  },
  {
    id: 'ex-shoulder-press-machine',
    name: 'Schulterpresse (Maschine)',
    muscle: 'shoulders',
    secondary: ['triceps'],
    equipment: 'machine',
    rest: 90,
    aliases: ['Schulterpresse', 'Schultermaschine', 'Shoulder Press'],
  },
  {
    id: 'ex-lateral-raise',
    name: 'Seitheben (Kurzhantel)',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Seitheben', 'Lateral Raises'],
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Seitheben am Kabel',
    muscle: 'shoulders',
    equipment: 'cable',
    unilateral: true,
    rest: 60,
    aliases: ['Kabel Seitheben', 'Cable Lateral Raise'],
  },
  {
    id: 'ex-lateral-raise-machine',
    name: 'Seitheben (Maschine)',
    muscle: 'shoulders',
    equipment: 'machine',
    rest: 60,
    aliases: ['Seitheben Maschine'],
  },
  {
    id: 'ex-front-raise',
    name: 'Frontheben',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Front Raises'],
  },
  {
    id: 'ex-reverse-fly-machine',
    name: 'Reverse Butterfly (Maschine)',
    muscle: 'shoulders',
    secondary: ['back'],
    equipment: 'machine',
    rest: 60,
    aliases: ['Reverse Butterfly', 'Reverse Flys', 'Butterfly reverse'],
  },
  {
    id: 'ex-face-pull',
    name: 'Face Pulls',
    muscle: 'shoulders',
    secondary: ['back'],
    equipment: 'cable',
    rest: 60,
    aliases: ['Facepulls', 'Face Pull'],
  },
  {
    id: 'ex-arnold-press',
    name: 'Arnold Press',
    muscle: 'shoulders',
    secondary: ['triceps'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 90,
    aliases: ['Arnold Presse'],
  },
  {
    id: 'ex-upright-row',
    name: 'Aufrechtes Rudern',
    muscle: 'shoulders',
    secondary: ['back'],
    equipment: 'barbell',
    barMode: 'included',
    rest: 60,
    aliases: ['Upright Row'],
  },

  // --- Bizeps ----------------------------------------------------------------
  {
    id: 'ex-seated-biceps-curl-bar',
    name: 'Bizepscurls sitzend (beidhändig)',
    muscle: 'biceps',
    secondary: ['forearms'],
    equipment: 'barbell',
    weightMode: 'per_side',
    barMode: 'excluded',
    rest: 60,
    aliases: ['Bizeps beidhängig im Sitzen', 'Bizeps beidhändig im Sitzen', 'Bizepscurls sitzend'],
  },
  {
    id: 'ex-cable-hammer-curl-rope',
    name: 'Hammercurls am Kabel (Seil)',
    muscle: 'biceps',
    secondary: ['forearms'],
    equipment: 'cable',
    rest: 60,
    aliases: ['Hammercurls am Kabel mit Seil', 'Hammercurls am Kabel', 'Seil Hammercurls', 'Rope Hammer Curl'],
  },
  {
    id: 'ex-barbell-curl',
    name: 'Langhantel-Curls',
    muscle: 'biceps',
    secondary: ['forearms'],
    equipment: 'barbell',
    barMode: 'included',
    rest: 60,
    aliases: ['Langhantelcurls', 'Barbell Curl'],
  },
  {
    id: 'ex-ez-curl',
    name: 'SZ-Curls',
    muscle: 'biceps',
    secondary: ['forearms'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 10,
    rest: 60,
    aliases: ['SZ Curls', 'EZ Curls', 'SZ-Stangen-Curls'],
  },
  {
    id: 'ex-db-curl',
    name: 'Kurzhantel-Curls',
    muscle: 'biceps',
    secondary: ['forearms'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Bizepscurls', 'Kurzhantelcurls', 'Dumbbell Curls'],
  },
  {
    id: 'ex-hammer-curl',
    name: 'Hammercurls (Kurzhantel)',
    muscle: 'biceps',
    secondary: ['forearms'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Hammercurls', 'Hammer Curls'],
  },
  {
    id: 'ex-preacher-curl-machine',
    name: 'Scott-Curls (Maschine)',
    muscle: 'biceps',
    equipment: 'machine',
    rest: 60,
    aliases: ['Scottcurls', 'Scott Curls', 'Bizepsmaschine', 'Preacher Curl'],
  },
  {
    id: 'ex-cable-curl',
    name: 'Bizepscurls am Kabel',
    muscle: 'biceps',
    equipment: 'cable',
    rest: 60,
    aliases: ['Kabelcurls', 'Cable Curls'],
  },
  {
    id: 'ex-concentration-curl',
    name: 'Konzentrationscurls',
    muscle: 'biceps',
    equipment: 'dumbbell',
    unilateral: true,
    rest: 60,
    aliases: ['Concentration Curls'],
  },
  {
    id: 'ex-incline-db-curl',
    name: 'Schrägbank-Curls (Kurzhantel)',
    muscle: 'biceps',
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 60,
    aliases: ['Incline Curls'],
  },

  // --- Trizeps ---------------------------------------------------------------
  {
    id: 'ex-triceps-pushdown',
    name: 'Trizepsdrücken am Kabel (Stange)',
    muscle: 'triceps',
    equipment: 'cable',
    rest: 60,
    aliases: ['Trizepsdrücken', 'Trizeps am Kabel', 'Pushdown'],
  },
  {
    id: 'ex-triceps-rope-pushdown',
    name: 'Trizepsdrücken am Kabel (Seil)',
    muscle: 'triceps',
    equipment: 'cable',
    rest: 60,
    aliases: ['Trizeps Seil', 'Rope Pushdown'],
  },
  {
    id: 'ex-overhead-triceps-cable',
    name: 'Überkopf-Trizepsstrecken am Kabel',
    muscle: 'triceps',
    equipment: 'cable',
    rest: 60,
    aliases: ['Trizeps überkopf', 'Overhead Triceps Extension'],
  },
  {
    id: 'ex-skull-crusher',
    name: 'French Press (SZ-Stange)',
    muscle: 'triceps',
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 10,
    rest: 60,
    aliases: ['French Press', 'Stirndrücken', 'Skull Crusher'],
  },
  {
    id: 'ex-dip-machine',
    name: 'Dipmaschine',
    muscle: 'triceps',
    secondary: ['chest'],
    equipment: 'machine',
    rest: 90,
    aliases: ['Dip Maschine', 'Trizepsmaschine Dips'],
  },
  {
    id: 'ex-bench-dips',
    name: 'Bankdips',
    muscle: 'triceps',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 60,
    aliases: ['Bench Dips'],
  },
  {
    id: 'ex-close-grip-bench',
    name: 'Enges Bankdrücken',
    muscle: 'triceps',
    secondary: ['chest'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 120,
    aliases: ['Close Grip Bench Press'],
  },
  {
    id: 'ex-db-kickback',
    name: 'Trizeps-Kickbacks',
    muscle: 'triceps',
    equipment: 'dumbbell',
    unilateral: true,
    rest: 60,
    aliases: ['Kickbacks'],
  },
  {
    id: 'ex-triceps-machine',
    name: 'Trizepsmaschine',
    muscle: 'triceps',
    equipment: 'machine',
    rest: 60,
    aliases: ['Trizeps Maschine'],
  },

  // --- Unterarme -------------------------------------------------------------
  {
    id: 'ex-wrist-curl',
    name: 'Unterarmcurls',
    muscle: 'forearms',
    equipment: 'barbell',
    rest: 60,
    aliases: ['Handgelenkcurls', 'Wrist Curls'],
  },

  // --- Bauch -----------------------------------------------------------------
  {
    id: 'ex-ab-crunch-machine',
    name: 'Crunch an der Bauchmaschine',
    muscle: 'abs',
    equipment: 'machine',
    rest: 60,
    aliases: ['Bauchmaschine Crunch', 'Bauchmaschine', 'Crunch Maschine', 'Ab Crunch Machine'],
  },
  {
    id: 'ex-captains-chair-leg-raise',
    name: 'Beinheben am Dipbarren',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 60,
    aliases: ['Dipbarren Bauchmuskel', 'Dipbarren Bauch', 'Knieheben am Dipbarren', "Captain's Chair"],
  },
  {
    id: 'ex-crunches',
    name: 'Crunches',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 45,
    aliases: ['Crunch', 'Bauchpressen'],
  },
  {
    id: 'ex-cable-crunch',
    name: 'Kabel-Crunches (kniend)',
    muscle: 'abs',
    equipment: 'cable',
    rest: 60,
    aliases: ['Kabelcrunch', 'Cable Crunch'],
  },
  {
    id: 'ex-hanging-leg-raise',
    name: 'Beinheben hängend',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 60,
    aliases: ['Hängendes Beinheben', 'Hanging Leg Raise'],
  },
  {
    id: 'ex-plank',
    name: 'Unterarmstütz (Plank)',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'time',
    rest: 60,
    aliases: ['Plank', 'Planke', 'Unterarmstütz'],
  },
  {
    id: 'ex-side-plank',
    name: 'Seitstütz',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'time',
    unilateral: true,
    rest: 45,
    aliases: ['Side Plank', 'Seitlicher Unterarmstütz'],
  },
  {
    id: 'ex-russian-twist',
    name: 'Russian Twists',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 45,
    aliases: ['Russian Twist'],
  },
  {
    id: 'ex-ab-wheel',
    name: 'Bauchroller (Ab Wheel)',
    muscle: 'abs',
    equipment: 'other',
    tracking: 'reps',
    rest: 60,
    aliases: ['Ab Roller', 'Ab Wheel', 'Bauchroller'],
  },
  {
    id: 'ex-sit-ups',
    name: 'Sit-ups',
    muscle: 'abs',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 45,
    aliases: ['Situps'],
  },
  {
    id: 'ex-rotary-torso',
    name: 'Rumpfrotation (Maschine)',
    muscle: 'abs',
    equipment: 'machine',
    unilateral: true,
    rest: 60,
    aliases: ['Rotationsmaschine', 'Rotary Torso'],
  },

  // --- Beine & Po ------------------------------------------------------------
  {
    id: 'ex-squat',
    name: 'Kniebeugen (Langhantel)',
    muscle: 'quads',
    secondary: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 180,
    aliases: ['Kniebeugen', 'Kniebeuge', 'Squats', 'Squat'],
  },
  {
    id: 'ex-front-squat',
    name: 'Frontkniebeugen',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 180,
    aliases: ['Front Squat'],
  },
  {
    id: 'ex-smith-squat',
    name: 'Kniebeugen an der Multipresse',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'smith',
    rest: 150,
    aliases: ['Multipresse Kniebeugen'],
  },
  {
    id: 'ex-leg-press',
    name: 'Beinpresse',
    muscle: 'quads',
    secondary: ['glutes', 'hamstrings'],
    equipment: 'machine',
    rest: 120,
    aliases: ['Leg Press'],
  },
  {
    id: 'ex-hack-squat',
    name: 'Hackenschmidt (Hack Squat)',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'machine',
    rest: 150,
    aliases: ['Hack Squat', 'Hackenschmidt'],
  },
  {
    id: 'ex-leg-extension',
    name: 'Beinstrecker (Maschine)',
    muscle: 'quads',
    equipment: 'machine',
    rest: 60,
    aliases: ['Beinstrecker', 'Leg Extension'],
  },
  {
    id: 'ex-leg-curl-lying',
    name: 'Beinbeuger liegend',
    muscle: 'hamstrings',
    equipment: 'machine',
    rest: 60,
    aliases: ['Beinbeuger', 'Leg Curl'],
  },
  {
    id: 'ex-leg-curl-seated',
    name: 'Beinbeuger sitzend',
    muscle: 'hamstrings',
    equipment: 'machine',
    rest: 60,
    aliases: ['Seated Leg Curl'],
  },
  {
    id: 'ex-rdl',
    name: 'Rumänisches Kreuzheben',
    muscle: 'hamstrings',
    secondary: ['glutes', 'back'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 120,
    aliases: ['Romanian Deadlift', 'RDL', 'Kreuzheben gestreckt'],
  },
  {
    id: 'ex-lunges',
    name: 'Ausfallschritte (Kurzhantel)',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    rest: 90,
    aliases: ['Ausfallschritte', 'Lunges'],
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squats',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    unilateral: true,
    rest: 90,
    aliases: ['Bulgarische Kniebeugen', 'Split Squats'],
  },
  {
    id: 'ex-goblet-squat',
    name: 'Goblet Squats',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'kettlebell',
    rest: 90,
    aliases: ['Goblet Squat'],
  },
  {
    id: 'ex-step-ups',
    name: 'Step-ups',
    muscle: 'quads',
    secondary: ['glutes'],
    equipment: 'dumbbell',
    weightMode: 'per_side',
    unilateral: true,
    rest: 60,
    aliases: ['Step ups', 'Aufsteiger'],
  },
  {
    id: 'ex-hip-thrust',
    name: 'Hip Thrust (Langhantel)',
    muscle: 'glutes',
    secondary: ['hamstrings'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 120,
    aliases: ['Hip Thrust', 'Hip Thrusts'],
  },
  {
    id: 'ex-glute-kickback-machine',
    name: 'Glute Kickback (Maschine)',
    muscle: 'glutes',
    equipment: 'machine',
    unilateral: true,
    rest: 60,
    aliases: ['Gesäßmaschine', 'Glute Kickback'],
  },
  {
    id: 'ex-abductor',
    name: 'Abduktoren (Maschine)',
    muscle: 'glutes',
    equipment: 'machine',
    rest: 60,
    aliases: ['Abduktorenmaschine', 'Abduktoren', 'Hip Abduction'],
  },
  {
    id: 'ex-adductor',
    name: 'Adduktoren (Maschine)',
    muscle: 'quads',
    equipment: 'machine',
    rest: 60,
    aliases: ['Adduktorenmaschine', 'Adduktoren', 'Hip Adduction'],
  },
  {
    id: 'ex-calf-raise-standing',
    name: 'Wadenheben stehend',
    muscle: 'calves',
    equipment: 'machine',
    rest: 60,
    aliases: ['Wadenheben', 'Calf Raises', 'Wadenmaschine'],
  },
  {
    id: 'ex-calf-raise-seated',
    name: 'Wadenheben sitzend',
    muscle: 'calves',
    equipment: 'machine',
    rest: 60,
    aliases: ['Seated Calf Raise'],
  },

  // --- Ganzkörper ------------------------------------------------------------
  {
    id: 'ex-kettlebell-swing',
    name: 'Kettlebell Swings',
    muscle: 'full_body',
    secondary: ['glutes', 'hamstrings'],
    equipment: 'kettlebell',
    rest: 90,
    aliases: ['KB Swings', 'Kettlebell Swing'],
  },
  {
    id: 'ex-burpees',
    name: 'Burpees',
    muscle: 'full_body',
    equipment: 'bodyweight',
    tracking: 'reps',
    rest: 60,
    aliases: ['Burpee'],
  },
  {
    id: 'ex-power-clean',
    name: 'Umsetzen (Power Clean)',
    muscle: 'full_body',
    secondary: ['back', 'quads'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 150,
    aliases: ['Power Clean', 'Umsetzen'],
  },
  {
    id: 'ex-thruster',
    name: 'Thruster',
    muscle: 'full_body',
    secondary: ['quads', 'shoulders'],
    equipment: 'barbell',
    barMode: 'included',
    barWeight: 20,
    rest: 120,
    aliases: ['Thrusters'],
  },
];
